---
- name: "Application deployment"
  hosts: "server"
  become: true
  vars_files:
    - defaults/main.yml
  roles:
   - { role: geerlingguy.nginx }
   - postgres
   - app_xpaste

  tasks:
  - name: "Reload nginx"
    ansible.builtin.service:
      name: "nginx"
      state: "reloaded"

  - name: "Print app url"
    ansible.builtin.debug:
      msg: "{{ APP_NAME }} available at: http://{{ ansible_ssh_host }}"